#!/usr/bin/env python3
"""
SPR{K}3 Vulnerability JSON Processor
Applies false positive filter and generates cleaned reports
"""

import json
import sys
from pathlib import Path
from sprk3_false_positive_filter import FalsePositiveFilter
from typing import Dict, List


class VulnerabilityProcessor:
    """Process scanner JSON output and apply filtering"""
    
    def __init__(self, json_file: str):
        self.json_file = json_file
        self.filter_engine = FalsePositiveFilter()
        self.raw_data = None
        self.filtered_data = None
        self.stats = {}
    
    def load_json(self) -> bool:
        """Load vulnerability JSON file"""
        try:
            with open(self.json_file, 'r') as f:
                self.raw_data = json.load(f)
            print(f"✓ Loaded {self.json_file}")
            return True
        except Exception as e:
            print(f"✗ Failed to load JSON: {e}")
            return False
    
    def process(self) -> bool:
        """Apply false positive filter to all vulnerabilities"""
        if not self.raw_data:
            print("✗ No data loaded. Run load_json() first.")
            return False
        
        vulnerabilities = self.raw_data.get('vulnerabilities', [])
        print(f"\n📊 Processing {len(vulnerabilities)} vulnerabilities...")
        
        # Apply filter
        filtered_vulns, filter_stats = self.filter_engine.process_batch(vulnerabilities)
        
        # Prepare output
        self.filtered_data = {
            'metadata': self.raw_data.get('metadata', {}),
            'filter_stats': filter_stats,
            'vulnerabilities': filtered_vulns,
            'summary': self._generate_summary(filtered_vulns, filter_stats)
        }
        
        return True
    
    def _generate_summary(self, vulns: List[Dict], stats: Dict) -> Dict:
        """Generate summary statistics"""
        
        # Group by severity
        by_severity = {}
        by_type = {}
        by_company = {}
        by_confidence = {'0.8-0.9': 0, '0.9-1.0': 0, '<0.8': 0}
        
        total_bounty = 0
        
        for vuln in vulns:
            severity = vuln.get('severity', 'UNKNOWN')
            vuln_type = vuln.get('type', 'UNKNOWN')
            company = vuln.get('company', 'UNKNOWN')
            confidence = vuln.get('confidence', 0)
            bounty_low = vuln.get('bounty_low', 0)
            
            by_severity[severity] = by_severity.get(severity, 0) + 1
            by_type[vuln_type] = by_type.get(vuln_type, 0) + 1
            by_company[company] = by_company.get(company, 0) + 1
            total_bounty += bounty_low
            
            if 0.8 <= confidence <= 0.9:
                by_confidence['0.8-0.9'] += 1
            elif confidence > 0.9:
                by_confidence['0.9-1.0'] += 1
            else:
                by_confidence['<0.8'] += 1
        
        return {
            'total_vulnerabilities': len(vulns),
            'false_positives_removed': stats.get('filtered', 0),
            'total_analyzed': stats.get('total', 0),
            'false_positive_rate': f"{100 * stats.get('filtered', 0) / max(1, stats.get('total', 1)):.1f}%",
            'estimated_bounty_potential': total_bounty,
            'by_severity': by_severity,
            'by_type': by_type,
            'by_company': by_company,
            'by_confidence': by_confidence,
            'reasons_filtered': stats.get('by_reason', {}),
        }
    
    def save_filtered_json(self, output_file: str = None) -> bool:
        """Save filtered results to JSON"""
        if not self.filtered_data:
            print("✗ No filtered data. Run process() first.")
            return False
        
        output_file = output_file or self.json_file.replace('.json', '_filtered.json')
        
        try:
            with open(output_file, 'w') as f:
                json.dump(self.filtered_data, f, indent=2)
            print(f"✓ Saved filtered JSON to {output_file}")
            return True
        except Exception as e:
            print(f"✗ Failed to save JSON: {e}")
            return False
    
    def generate_markdown_report(self, output_file: str = None) -> bool:
        """Generate markdown report of filtered vulnerabilities"""
        if not self.filtered_data:
            print("✗ No filtered data. Run process() first.")
            return False
        
        output_file = output_file or self.json_file.replace('.json', '_report_filtered.md')
        
        summary = self.filtered_data['summary']
        vulns = self.filtered_data['vulnerabilities']
        
        report = []
        report.append("# SPR{K}3 Filtered Vulnerability Report\n")
        report.append("*Generated by SPR{K}3 False Positive Filter*\n")
        
        # Summary section
        report.append("## Summary\n")
        report.append(f"**Analysis Date**: {self.filtered_data['metadata'].get('scan_date', 'Unknown')}\n")
        report.append(f"**Total Vulnerabilities Found**: {summary['total_analyzed']}\n")
        report.append(f"**False Positives Filtered**: {summary['false_positives_removed']} ({summary['false_positive_rate']})\n")
        report.append(f"**Real Vulnerabilities**: {summary['total_vulnerabilities']}\n")
        report.append(f"**Estimated Bounty Potential**: ${summary['estimated_bounty_potential']:,}\n\n")
        
        # Breakdown by severity
        report.append("## Vulnerability Breakdown\n")
        report.append("### By Severity\n")
        for severity, count in sorted(summary['by_severity'].items(), reverse=True):
            report.append(f"- **{severity}**: {count}\n")
        
        report.append("\n### By Type\n")
        for vuln_type, count in sorted(summary['by_type'].items(), key=lambda x: x[1], reverse=True):
            report.append(f"- **{vuln_type}**: {count}\n")
        
        report.append("\n### By Company\n")
        for company, count in sorted(summary['by_company'].items(), key=lambda x: x[1], reverse=True):
            report.append(f"- **{company}**: {count}\n")
        
        # Confidence distribution
        report.append("\n## Confidence Analysis\n")
        report.append("Vulnerabilities are grouped by confidence level:\n")
        for confidence_range, count in summary['by_confidence'].items():
            pct = 100 * count / max(1, summary['total_vulnerabilities'])
            report.append(f"- **{confidence_range}**: {count} ({pct:.1f}%)\n")
        
        # Reasons for filtering
        if summary['false_positives_removed'] > 0:
            report.append("\n## Why Findings Were Filtered\n")
            for reason, count in sorted(
                summary['reasons_filtered'].items(),
                key=lambda x: x[1],
                reverse=True
            ):
                pct = 100 * count / summary['total_analyzed']
                report.append(f"- **{reason}**: {count} ({pct:.1f}%)\n")
        
        # Detailed findings
        report.append("\n## Detailed Findings\n")
        report.append("⚠️ **These are the real vulnerabilities that passed filtering**\n\n")
        
        # Group by company
        by_company = {}
        for vuln in vulns:
            company = vuln.get('company', 'UNKNOWN')
            if company not in by_company:
                by_company[company] = []
            by_company[company].append(vuln)
        
        for company in sorted(by_company.keys()):
            company_vulns = by_company[company]
            report.append(f"### {company} ({len(company_vulns)} vulnerabilities)\n\n")
            
            for i, vuln in enumerate(company_vulns, 1):
                report.append(f"**Finding #{i}**\n")
                report.append(f"- **Type**: {vuln.get('type', 'UNKNOWN')}\n")
                report.append(f"- **Severity**: {vuln.get('severity', 'UNKNOWN')}\n")
                report.append(f"- **Confidence**: {vuln.get('confidence', 0):.2f}\n")
                report.append(f"- **File**: {vuln.get('file', 'Unknown')}\n")
                report.append(f"- **Line**: {vuln.get('line', 'Unknown')}\n")
                report.append(f"- **Code**:\n```python\n{vuln.get('code', 'N/A')}\n```\n")
                report.append(f"- **Filter Note**: {vuln.get('filter_reason', 'N/A')}\n")
                
                if vuln.get('bounty_low'):
                    report.append(f"- **Bounty Range**: ${vuln['bounty_low']:,} - ${vuln.get('bounty_high', 0):,}\n")
                
                report.append("\n---\n\n")
        
        # Footer
        report.append("\n## Notes\n")
        report.append("- ⚠️ Verify findings before submitting to bug bounty programs\n")
        report.append("- 💡 Some findings may still need manual review\n")
        report.append("- 🔒 All submissions should include proof-of-concept if applicable\n")
        report.append("- 📋 Always follow program's responsible disclosure policy\n")
        
        try:
            with open(output_file, 'w') as f:
                f.write(''.join(report))
            print(f"✓ Saved markdown report to {output_file}")
            return True
        except Exception as e:
            print(f"✗ Failed to save report: {e}")
            return False
    
    def print_summary(self):
        """Print filtering summary to console"""
        if not self.filtered_data:
            print("✗ No filtered data. Run process() first.")
            return
        
        summary = self.filtered_data['summary']
        
        print("\n" + "="*70)
        print("SPR{K}3 FILTERED RESULTS SUMMARY")
        print("="*70)
        print(f"\nTotal Analyzed: {summary['total_analyzed']}")
        print(f"False Positives: {summary['false_positives_removed']} ({summary['false_positive_rate']})")
        print(f"Real Vulnerabilities: {summary['total_vulnerabilities']}")
        print(f"Estimated Bounty: ${summary['estimated_bounty_potential']:,}")
        
        print("\nBy Severity:")
        for severity, count in sorted(summary['by_severity'].items(), reverse=True):
            print(f"  {severity}: {count}")
        
        print("\nBy Company:")
        for company, count in sorted(summary['by_company'].items(), key=lambda x: x[1], reverse=True):
            print(f"  {company}: {count}")
        
        print("\nBy Confidence:")
        for confidence, count in summary['by_confidence'].items():
            pct = 100 * count / max(1, summary['total_vulnerabilities'])
            print(f"  {confidence}: {count} ({pct:.1f}%)")
        
        print("\n" + "="*70 + "\n")


# ============ USAGE ============

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python3 sprk3_processor.py <json_file>")
        print("Example: python3 sprk3_processor.py sprk3_vulnerabilities.json")
        sys.exit(1)
    
    json_file = sys.argv[1]
    
    # Process
    processor = VulnerabilityProcessor(json_file)
    
    if not processor.load_json():
        sys.exit(1)
    
    if not processor.process():
        sys.exit(1)
    
    processor.print_summary()
    
    # Save outputs
    processor.save_filtered_json()
    processor.generate_markdown_report()
    
    print("✓ Processing complete!")
